
modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="dyeable_flower_pots" #mandatory
version="1.15.2-1.1.0" #mandatory
displayName="Dyeable Flower Pots" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/dyeable-flower-pots" #optional
# logoFile="examplemod.png" #optional
credits="Wyn-Price for his super practical CurseMaven plugin" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Dye your flower pots! Now compatible with Biomes O Plenty and Quark.
'''
[[dependencies.dyeable_flower_pots]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dyeable_flower_pots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dyeable_flower_pots]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[1.15.2-10.0.0.353,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dyeable_flower_pots]]
    modId="autoreglib"
    mandatory=false
    versionRange="[1.5-40,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dyeable_flower_pots]]
    modId="quark"
    mandatory=false
    versionRange="[r2.1-245,)"
    ordering="AFTER"
    side="BOTH"