
modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="dyeable_flower_pots" #mandatory
version="1.15.2-1.1.0" #mandatory
displayName="Example Mod" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
e
'''
[[dependencies.dyeable_flower_pots]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.29,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dyeable_flower_pots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dyeable_flower_pots]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[1.15.2-10.0.0.353,)"
    ordering="AFTER"
    side="BOTH"